apiVersion: v1
kind: Service
metadata:
  name: postgresql
  labels:
    "xdatabase-proxy-enabled": "true"
    "xdatabase-proxy-deployment-id": "team-1992252154561"
    "xdatabase-proxy-database-type": "postgresql"
    "xdatabase-proxy-pooled": "false"
    "xdatabase-proxy-destination-port": "5432"
spec:
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgresql
  selector:
    app: postgresql
