apiVersion: apps/v1
kind: Deployment
metadata:
  name: xdatabase-proxy
spec:
  selector:
    matchLabels:
      app: xdatabase-proxy
  template:
    metadata:
      labels:
        app: xdatabase-proxy
    spec:
      serviceAccountName: xdatabase-proxy-sa
      containers:
        - name: xdatabase-proxy
          image: ghcr.io/hasirciogli/xdatabase-proxy:latest
          ports:
            - containerPort: 1881
              name: proxy-port
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /healthz
              port: 80
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3
            successThreshold: 1
          readinessProbe:
            httpGet:
              path: /ready
              port: 80
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
            successThreshold: 1
